# requiring the environment of NodeJS 10
image: goffinet/gitbook:gitlab

before_script:
  - gitbook install # add any requested plugins in book.json

# the 'pdf' job will build your document in pdf format
pdf:
  stage: build
  script:
    - gitbook build . pdf . ${CI_PROJECT_NAME}.pdf # pdf build
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}.pdf
    expire_in: 1 day
  only:
    - master # this job will affect only the 'master' branch the 'pdf' job will build your document in pdf format
# the 'epub' job will build your document in epub format
epub:
  stage: build
  script:
    - gitbook build . epub . ${CI_PROJECT_NAME}.epub # epub build
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}.epub
    expire_in: 1 day
  only:
    - master # this job will affect only the 'master' branch
