- name: delete buckets
  hosts: localhost
  vars:
    buckets:
      - cf-templates-188123uubvcny-eu-west-3
  tasks:
    - name: Delete a bucket and all contents
      aws_s3:
        bucket: "{{ item }}"
        mode: delete
      loop: "{{ buckets }}"
