---
- name: Deploy S3 Static Website
  hosts: localhost
  vars:
    BUCKET_NAME: "{{ ansible_date_time.iso8601_micro | to_uuid }}" # random bucket name
    BUCKET_REGION: "eu-west-3"
    SOURCE_PATH: /tmp/website
  tasks:
    - name: create a website directory to host the website files
      file:
        path: "{{ SOURCE_PATH }}"
        state: directory
    - name: create a index.html file
      copy:
        dest: "{{ SOURCE_PATH }}/index.html"
        content: |
          <html xmlns="http://www.w3.org/1999/xhtml" >
          <head>
              <title>My Website Home Page {{ BUCKET_NAME }}</title>
          </head>
          <body>
            <h1>Welcome to my website {{ BUCKET_NAME }}</h1>
            <p>Now hosted on Amazon S3!</p>
          </body>
          </html>
    - name: Create a bucket and attach policy
      s3_bucket:
        name: "{{ BUCKET_NAME }}"
        state: present
        region: "{{ BUCKET_REGION }}"
        policy:
          Version: '2012-10-17'
          Statement:
          - Sid: Allow Public Access to All Objects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: arn:aws:s3:::{{ BUCKET_NAME }}/*
    - name: set website configuration index/error file
      s3_website:
        name: "{{ BUCKET_NAME }}"
        state: present
        error_key: error.html
    - name: synchronize the files
      s3_sync:
        bucket: "{{ BUCKET_NAME }}"
        file_root: "{{ SOURCE_PATH }}/"
        permission: public-read
        delete: yes
    - name: 5 sec. waiting
      pause:
        seconds: 5
        prompt: "Please check the URL http://{{ BUCKET_NAME }}.s3-website.{{ BUCKET_REGION }}.amazonaws.com/"
    - name: test the website
      uri:
        url: "http://{{ BUCKET_NAME }}.s3-website.{{ BUCKET_REGION }}.amazonaws.com/"
        return_content: yes
      register: thepage
      failed_when: "'{{ BUCKET_NAME }}' not in thepage.content"
    - name: 3 minutes waiting before deleting the bucket
      pause:
        minutes: 3
    - name: Delete a bucket and all contents
      aws_s3:
        bucket: "{{ BUCKET_NAME }}"
        mode: delete
