---
# defaults file for mediapeers.s3-website-hosting

website_root: 'website/'
# S3 bucket settings:
s3_website_bucket_name: 'my-website-s3-bucket'
s3_website_bucket_region: 'us-east-1'
# Domain names should be covered by the given TLS certificate:
s3_website_alias_domain_names:
  - 'custom-domain.org'
  - 'other-domain.org'
# Use TLS certificate created with AWS certificate manager (ACM):
s3_website_certificate_arn: 'tls-certificate-arn-for-cloudwatch'
s3_website_create_dns_record: true

# Root documents for your website:
s3_website_root_object: 'index.html'

# Cloufront cache tuning:
# max seconds items can stay in the cache
s3_website_caching_max_ttl: 2592000 # 30 days (AWS defaults to 365 days)
# seconds after which the origin is checked for a change
s3_website_caching_default_ttl: 86400 # 1 day (AWS default)

# Other cloudfront settings:

# TLS protocol policy string for Clodufront config
s3_website_cloudfront_tls_policy: TLSv1.1_2016

# PriceClass option for CloudFront
s3_website_price_class: PriceClass_100

# Cloudfront Lambda function (aka Lambda@Edge)
# useful for example to return custom headers (security headers etc.)
s3_website_cloudfront_lambda_functions: []
# Add dicts to this list like this to add lambda function to the Cloudfront distribution:
# { lambda_function_arn: arn:aws:lambda:us-east-1:123123123:function:my-function-name:10, event_type: 'origin-response', include_body: false }
